version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.18.2
      - image: circleci/mongo:3.6.3
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Seed database
          command: npm run seed
      - run:
         name: Test
        command: npm run test